# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026, UAB Kurokesu. All rights reserved.

PACKAGE_NAME="os08e10-rpi-dkms"
PACKAGE_VERSION="0.1.1"

BUILT_MODULE_NAME="os08e10"
BUILT_MODULE_LOCATION="build"
DEST_MODULE_LOCATION="/updates"

MAKE="make module KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"

POST_INSTALL="dkms.postinst"

AUTOINSTALL="yes"
