[DEFAULT]
debian-branch = debian/latest
upstream-branch = main
upstream-tag = v%(version)s
upstream-vcs-tag = v%(version)s
debian-tag = debian/%(version)s
pristine-tar = False

[dch]
multimaint-merge = True

[pq]
patch-numbers = False
